-- MySQL Script generated by MySQL Workbench
-- Sun Mar 20 14:43:55 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema remedios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema remedios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `remedios` DEFAULT CHARACTER SET latin1 ;
USE `remedios` ;

-- -----------------------------------------------------
-- Table `remedios`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `remedios`.`usuarios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(255) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `senha` CHAR(40) NOT NULL COMMENT '',
  `ativo` CHAR(1) NOT NULL DEFAULT '1' COMMENT '',
  `ultimoAcesso` DATETIME NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

INSERT INTO `usuarios` (`nome`, `email`, `senha`, `ativo`, `ultimoAcesso`, `created`, `updated`) VALUES
('Guilherme Jr.', 'falecom@guilhermejr.net', '848d3ee0d1ac67f1f78c1b43e8001a7a6fae1050', '1', '2014-12-31 10:46:33', '2014-08-18 16:38:15', '2014-12-31 10:46:33');


-- -----------------------------------------------------
-- Table `remedios`.`indicacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `remedios`.`indicacoes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(255) NOT NULL COMMENT '',
  `usuario_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_indicacoes_usuarios1_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_indicacoes_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `remedios`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `remedios`.`remedios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `remedios`.`remedios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(255) NOT NULL COMMENT '',
  `contraIndicacao` TEXT NOT NULL COMMENT '',
  `posologia` TEXT NOT NULL COMMENT '',
  `qtd` INT NOT NULL COMMENT '',
  `validade` DATE NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NOT NULL COMMENT '',
  `usuario_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_remedios_usuarios_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_remedios_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `remedios`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `remedios`.`indicacoes_remedios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `remedios`.`indicacoes_remedios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `indicacao_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `remedio_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `indicacao_id`, `remedio_id`)  COMMENT '',
  INDEX `fk_indicacoes_has_remedios_remedios1_idx` (`remedio_id` ASC)  COMMENT '',
  INDEX `fk_indicacoes_has_remedios_indicacoes1_idx` (`indicacao_id` ASC)  COMMENT '',
  CONSTRAINT `fk_indicacoes_has_remedios_indicacoes1`
    FOREIGN KEY (`indicacao_id`)
    REFERENCES `remedios`.`indicacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicacoes_has_remedios_remedios1`
    FOREIGN KEY (`remedio_id`)
    REFERENCES `remedios`.`remedios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `remedios`.`senhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `remedios`.`senhas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `hash` CHAR(40) NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `updated` DATETIME NULL COMMENT '',
  `usuario_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_senhas_usuarios1_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_senhas_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `remedios`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `remedios`.`configuracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `remedios`.`configuracoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `vencido` CHAR(1) BINARY NOT NULL DEFAULT '1' COMMENT 'Enviar e-mail quando um remédios estiver vencido',
  `avencer` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Enviar e-mail quando um remédio estiver para vencer',
  `dias` INT NOT NULL DEFAULT 30 COMMENT 'Dias de antecedência que começará a ser avisado por e-mail que um remédio irá vencer. ',
  `periodicidade` ENUM('dia', 'semana', 'mes') NOT NULL DEFAULT 'dia' COMMENT 'Periodicidade que recede os e-mail. Se for semana, receberá todo domingo, se for mes, receberá todo dia 01',
  `usuario_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_configuracoes_usuarios1_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_configuracoes_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `remedios`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `configuracoes` (`vencido`, `avencer`, `dias`, `periodicidade`, `usuario_id`) VALUES
('1', '1', 30, 'dia', 1);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
